theme: jekyll-theme-minimal
title: Scratch
description: A bucket for open ideas I want to work on.

I am a research scientist interested in IPv6 growth and deployment. I've spent a lot of time deploying IPv6 during the years where IPv6 growth was genuinely new. We're now at a point where it's real, and we need to understand it.

