theme: jekyll-theme-minimal
title: Dr Stephen Strowes
description: I'm a Principal Engineer in the Office of the CTO at Fastly. Formerly R&D at the RIPE NCC, IPv6 deployment at Yahoo, network measurement at Boundary. PhD from University of Glasgow in 2012.

